[package]
name = "sp1-prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp1-recursion-program = { path = "../recursion/program" }
sp1-recursion-circuit = { path = "../recursion/circuit" }
sp1-recursion-compiler = { path = "../recursion/compiler" }
sp1-recursion-core = { path = "../recursion/core" }
sp1-core = { path = "../core" }
sp1-sdk = { path = "../sdk" }
p3-field = { workspace = true }
p3-challenger = { workspace = true }
p3-baby-bear = { workspace = true }
p3-commit = { workspace = true }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive", "rc"] }
backtrace = "0.3.71"
rayon = "1.10.0"
itertools = "0.12.1"
tracing = "0.1.40"
serde_json = "1.0.116"
